import React from 'react';
import styles from './Footer.module.scss';

const Footer = () => {
  return (
    <footer className={styles["footer"]}>
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
      IUHOSADUIHXUD
    </footer>
  );
};

export default Footer;